title: CLazStudio
description: CLazStudio GitHub.io page
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman
theme_color: "#FF5722"
 
google_verify: L9JqXfHjSoVdD_iVCeqDjsNGnhxv26q4BBvhsWeQ980
repository: clazstudio/clazstudio.github.io

plugins:
  - jekyll-mentions
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
